"use client";

import { useEffect, useMemo, useState } from "react";

type Campaign = {
  id: string;
  category: string;
  title: string;
  name: string;
  location: string;
  description: string;
  use: string;
  raised: number;
  goal: number;
  supporters: number;
  image: string;
  verified: boolean;
  flagship?: boolean;
  update: string;
};

const campaigns: Campaign[] = [
  { id:"kente", category:"Fashion & Trading", title:"Kente accessories for students", name:"Akosua Boateng", location:"Cape Coast, Ghana", description:"A UCC student selling handmade kente accessories on campus. She is raising starting stock and a stall fee to move from selling out of a backpack to a proper table.", use:"GHS 800 fabric & materials · GHS 400 first market stall fee", raised:780, goal:1200, supporters:34, image:"/images/kente.svg", verified:true, flagship:true, update:"We have reached 65% of our goal and are preparing our next batch of handmade pieces." },
  { id:"repair", category:"Services", title:"Mobile phone repair kiosk", name:"Kwabena Owusu", location:"Kumasi, Ghana", description:"A self-taught phone repair technician looking to set up a fixed kiosk near a busy market instead of working door-to-door.", use:"GHS 2,000 tools & parts · GHS 1,500 kiosk rental deposit", raised:1900, goal:3500, supporters:51, image:"/images/repair.svg", verified:true, update:"The first equipment purchase is ready once the campaign crosses the next milestone." },
  { id:"waakye", category:"Food & Delivery", title:"Waakye delivery service", name:"Efua Mensah", location:"Accra, Ghana", description:"A small home-based waakye business adding delivery so students and workers who cannot leave campus can still order.", use:"GHS 600 cooking equipment · GHS 300 delivery fuel fund", raised:900, goal:900, supporters:28, image:"/images/waakye.svg", verified:true, flagship:true, update:"Fully funded! The business is now serving more customers with its new delivery routine." },
  { id:"solar", category:"Agriculture", title:"Solar irrigation for a vegetable farm", name:"Kofi Asare", location:"Eastern Region, Ghana", description:"A young farmer wants to reduce fuel costs and keep a small vegetable plot productive during dry periods with a solar-powered irrigation setup.", use:"GHS 1,450 solar pump · GHS 550 pipes & storage", raised:1120, goal:2000, supporters:22, image:"/images/farm.svg", verified:false, update:"The farmer has secured the water tank and is raising the final amount for the solar pump." },
  { id:"design", category:"Technology", title:"Campus design & print studio", name:"Nana Yeboah", location:"Cape Coast, Ghana", description:"A student designer building a compact print and design service for clubs, student entrepreneurs and local events.", use:"GHS 1,200 printer · GHS 700 materials & workspace", raised:1340, goal:1900, supporters:37, image:"/images/design.svg", verified:true, update:"The campaign is 71% funded and has already received its first bulk printing request." },
  { id:"snacks", category:"Food & Trading", title:"Healthy snack packs for students", name:"Abena Ofori", location:"Takoradi, Ghana", description:"Affordable snack packs made from locally sourced ingredients, designed for students who need quick food between classes.", use:"GHS 600 ingredients · GHS 450 packaging · GHS 250 delivery", raised:520, goal:1300, supporters:16, image:"/images/snacks.svg", verified:false, update:"New sample packs are being tested with students before the next production run." }
];

const supporters = [
  ["Nana B.","Sponsor",6,2400],["Kojo Mensah","Investor",4,1600],["Priscilla O.","Supporter",3,950],["Yaw A.","Supporter",5,700]
] as const;

const defaultImpact = { entrepreneurs_funded:342, support_mobilized:342000, supporters:1200, average_progress:78 };
const defaultFaqs = [
  {question:"Who can create a campaign?",answer:"Young entrepreneurs, students and micro business owners can submit a business pitch. Campaigns are reviewed by the Peer Pockets administrator before publication."},
  {question:"How does support work?",answer:"Supporters choose a campaign and amount. The final production flow will use a secure Mobile Money Request to Pay provider so the payer receives a prompt on their own phone."},
  {question:"What does “Verified” mean?",answer:"A verification badge means the relevant identity and campaign information has passed the platform's review process. It should never be treated as a guarantee of business success."},
  {question:"Can I report a campaign?",answer:"Yes. Suspicious or misleading campaigns can be reported so concerns can be reviewed by the administrator and appropriate action can be taken."}
];

const categories = ["All","Fashion & Trading","Services","Food & Delivery","Agriculture","Technology"];
const learningResources = [
  {name:"Graphic design",group:"Business skills",description:"Create clear flyers, social posts and campaign images.",source:"Canva Design School",sourceUrl:"https://www.canva.com/designschool/",videoUrl:"https://www.youtube.com/results?search_query=graphic+design+for+beginners"},
  {name:"Digital marketing",group:"Business skills",description:"Reach the right customers with simple online campaigns.",source:"Google Digital Garage",sourceUrl:"https://learndigital.withgoogle.com/digitalgarage",videoUrl:"https://www.youtube.com/results?search_query=digital+marketing+for+beginners"},
  {name:"Coding",group:"Business skills",description:"Build useful tools and understand how digital products work.",source:"freeCodeCamp",sourceUrl:"https://www.freecodecamp.org/learn/",videoUrl:"https://www.youtube.com/results?search_query=coding+for+beginners"},
  {name:"Photography",group:"Business skills",description:"Take stronger product photos that help customers decide.",source:"Adobe Photography Basics",sourceUrl:"https://www.adobe.com/creativecloud/photography/discover/photography-basics.html",videoUrl:"https://www.youtube.com/results?search_query=product+photography+for+beginners"},
  {name:"Bookkeeping",group:"Business skills",description:"Track sales, costs and cash so you know how your business is doing.",source:"QuickBooks Accounting Guide",sourceUrl:"https://quickbooks.intuit.com/accounting/",videoUrl:"https://www.youtube.com/results?search_query=bookkeeping+for+small+business+beginners"},
  {name:"Copywriting",group:"Business skills",description:"Write words that explain your offer and invite people to act.",source:"Coursera Copywriting Guide",sourceUrl:"https://www.coursera.org/articles/copywriting",videoUrl:"https://www.youtube.com/results?search_query=copywriting+for+beginners"},
  {name:"Tailoring",group:"Practical trades",description:"Learn measurements, garment construction and finishing skills.",source:"Tailoring Learning Search",sourceUrl:"https://www.youtube.com/results?search_query=tailoring+for+beginners",videoUrl:"https://www.youtube.com/results?search_query=tailoring+for+beginners"},
  {name:"Shoemaking",group:"Practical trades",description:"Explore shoe patterns, cutting, assembly and repair.",source:"Shoemaking Learning Search",sourceUrl:"https://www.youtube.com/results?search_query=shoemaking+for+beginners",videoUrl:"https://www.youtube.com/results?search_query=shoemaking+for+beginners"},
  {name:"Plumbing",group:"Practical trades",description:"Understand fittings, water flow and safe repair basics.",source:"Plumbing Learning Search",sourceUrl:"https://www.youtube.com/results?search_query=plumbing+for+beginners",videoUrl:"https://www.youtube.com/results?search_query=plumbing+for+beginners"},
  {name:"Electrical work",group:"Practical trades",description:"Study circuits, tools and essential electrical safety.",source:"Electrical Learning Search",sourceUrl:"https://www.youtube.com/results?search_query=basic+electrical+work+for+beginners",videoUrl:"https://www.youtube.com/results?search_query=basic+electrical+work+for+beginners"},
  {name:"Welding",group:"Practical trades",description:"Learn equipment basics, joints, materials and workshop safety.",source:"Welding Learning Search",sourceUrl:"https://www.youtube.com/results?search_query=welding+for+beginners",videoUrl:"https://www.youtube.com/results?search_query=welding+for+beginners"},
  {name:"Carpentry",group:"Practical trades",description:"Build confidence with measuring, cutting and joining wood.",source:"Carpentry Learning Search",sourceUrl:"https://www.youtube.com/results?search_query=carpentry+for+beginners",videoUrl:"https://www.youtube.com/results?search_query=carpentry+for+beginners"},
  {name:"Hairdressing",group:"Practical trades",description:"Practice care, styling, hygiene and client service basics.",source:"Hairdressing Learning Search",sourceUrl:"https://www.youtube.com/results?search_query=hairdressing+for+beginners",videoUrl:"https://www.youtube.com/results?search_query=hairdressing+for+beginners"}
];

export default function Home() {
  const [modal, setModal] = useState<"support"|"pitch"|"campaign"|null>(null);
  const [selected, setSelected] = useState<Campaign|null>(null);
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("All");
  const [sort, setSort] = useState("featured");
  const [amount, setAmount] = useState("");
  const [phone, setPhone] = useState("");
  const [notice, setNotice] = useState("");
  const [paymentReference, setPaymentReference] = useState("");
  const [paymentState, setPaymentState] = useState<"idle"|"waiting"|"success">("idle");
  const [senderNetwork, setSenderNetwork] = useState("MTN Mobile Money");
  const [dbReady, setDbReady] = useState(false);
  const [liveCampaigns, setLiveCampaigns] = useState<Campaign[]>(campaigns);
  const [liveSupporters, setLiveSupporters] = useState<any[]>([...supporters]);
  const [siteContent, setSiteContent] = useState<any>({settings:{},faqs:[]});
  const [pitchSending, setPitchSending] = useState(false);
  const [pitchStudent, setPitchStudent] = useState("");
  const [pitchAdult, setPitchAdult] = useState("");
  useEffect(() => {
    Promise.all([fetch("/api/campaigns"),fetch("/api/site")]).then(async([campaignResponse,siteResponse])=>{
      const campaignData=campaignResponse.ok?await campaignResponse.json():null;
      const siteData=siteResponse.ok?await siteResponse.json():null;
      if(campaignData?.campaigns?.length){setDbReady(true);setLiveCampaigns(campaignData.campaigns.map((c:any)=>({...c,name:c.entrepreneur_name,image:c.image_url||c.image||"/images/hero.svg",flagship:c.featured,update:c.latest_update||""})));}
      if(siteData)setSiteContent({...siteData,faqs:Array.from(new Map((siteData.faqs||[]).map((faq:any)=>[faq.question,faq])).values())});
      if(siteData?.supporters?.length)setLiveSupporters(siteData.supporters.map((s:any)=>[s.display_name||"Anonymous supporter","Supporter",s.campaigns_supported||0,Number(s.total_supported||0)]));
    }).catch(() => {});
  }, []);

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    const list = liveCampaigns.filter(c => (category === "All" || c.category === category) && (!q || `${c.title} ${c.name} ${c.location} ${c.category}`.toLowerCase().includes(q)));
    return [...list].sort((a,b) => sort === "newest" ? b.id.localeCompare(a.id) : sort === "almost" ? (b.raised/b.goal)-(a.raised/a.goal) : sort === "most" ? b.supporters-a.supporters : (Number(b.flagship)-Number(a.flagship)) || (b.raised/b.goal)-(a.raised/a.goal));
  }, [liveCampaigns, search, category, sort]);
  const impact = {...defaultImpact,...(siteContent.settings?.impact||{})};
  const platform = siteContent.settings?.platform||{};
  const faqSource = siteContent.faqs?.length ? siteContent.faqs : defaultFaqs;
  const faqs = Array.from(new Map(faqSource.map((faq:any)=>[String(faq.question).trim().toLowerCase(),faq])).values());

  function openCampaign(c: Campaign) { setSelected(c); setModal("campaign"); }
  function openSupport(c: Campaign) { setSelected(c); setAmount(""); setPhone(""); setPaymentReference(""); setNotice(""); setPaymentState("idle"); setModal("support"); }
  function beginPayment() {
    const value = Number(amount);
    if (!selected || !value || value < 1 || !phone.trim()) { setNotice("Enter a valid amount and your Mobile Money number."); return; }
    setPaymentState("waiting");
    setNotice(`Payment details ready. For now, send GHS ${amount} to ${platform.momo_number||"050 012 6026"}, then enter your transaction/reference number below.`);
  }
  async function confirmPayment() {
    if (!paymentReference.trim()) { setNotice("Enter the transaction/reference number."); return; }
    try {
      const r = await fetch("/api/payments", {method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({campaign_id:selected?.id, amount:Number(amount), phone, network:senderNetwork, provider_reference:paymentReference})});
      if (!r.ok) throw new Error();
      setPaymentState("success"); setNotice("Payment confirmation submitted for admin verification.");
    } catch { setNotice("We could not save the payment confirmation. Please try again."); }
  }
  async function submitPitch(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setPitchSending(true); const form = new FormData(e.currentTarget); const applicationData = Object.fromEntries(Array.from(form.entries()).filter(([key]) => key !== "business_photo")); const photo = form.get("business_photo"); try { const r = await fetch("/api/pitches", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ title:form.get("business_name"), entrepreneur_name:form.get("full_name"), category:form.get("category"), goal:1000, story:form.get("business_description"), use_of_funds:form.get("funding_use"), location:form.get("location"), application_data:{...applicationData, business_photo:photo instanceof File && photo.name ? photo.name : ""} }) }); if (!r.ok) throw new Error(); setModal(null); setNotice("Your pitch has been submitted for admin review."); } catch { setNotice("The pitch form is ready, but the database must be connected in Render before submissions can be saved."); } finally { setPitchSending(false); } }

  return <main id="top">
    <header className="nav">
      <a href="#top" className="brand"><img src="/images/logo.svg" alt=""/><span>Peer Pockets</span></a>
      <nav className="nav-links"><a href="#discover">Discover</a><a href="#how-it-works">How it works</a><a href="#trust">Trust & safety</a><a href="#impact">Our impact</a></nav>
      <div className="nav-actions"><a className="learn-nav-link" href="#learn">Learn a skill</a><button className="pitch-btn" onClick={() => setModal("pitch")}>Pitch your business</button></div>
    </header>

    <section className="hero page-pad">
      <div className="hero-grid">
        <div><h1>Small capital.<br/><span>Real businesses.</span></h1><p className="hero-copy">We believe good businesses shouldn't fail because they started small. Peer Pockets connects young, student, and micro entrepreneurs with supporters who fund a clear next step.</p><div className="hero-actions"><a className="primary-link" href="#discover">Discover businesses <span>→</span></a><button className="secondary-link" onClick={() => setModal("pitch")}>Start a pitch</button></div><div className="trust-row"><span>✓ Clear funding goals</span><span>✓ Verified campaigns</span><span>✓ Entrepreneurship focused</span></div></div>
        <div className="hero-art"><img src="/images/hero.svg" alt="Young entrepreneurs growing businesses with community support"/><div className="hero-floating"><strong>GHS 342K+</strong><span>community support pledged</span></div></div>
      </div>
      <div className="program"><div><div className="gold">Flagship programme</div><h2>GHS 1,000 to 1,000 Entrepreneurs</h2><p>Support a cohort of young entrepreneurs with practical starting capital.</p></div><div className="program-stat"><strong>{impact.entrepreneurs_funded.toLocaleString()} / 1000</strong><span>entrepreneurs funded</span></div><div className="program-bar"><i style={{width:`${Math.min(100,Number(impact.entrepreneurs_funded)/10)}%`}}/></div></div>
    </section>

    <section id="how-it-works" className="section light-section page-pad"><div className="section-heading"><div><div className="eyebrow">Simple by design</div><h2 className="section-title">From an idea to a funded business</h2></div><p className="section-subtitle">A straightforward way for entrepreneurs to ask for what they need — and for supporters to back something tangible.</p></div><div className="steps"><div className="step"><div className="step-number">01</div><h3>Tell your story</h3><p>Share your business idea, funding goal, photos, and exactly what the money will buy.</p></div><div className="step"><div className="step-number">02</div><h3>Get discovered</h3><p>Your pitch is reviewed and presented clearly so supporters can understand the opportunity.</p></div><div className="step"><div className="step-number">03</div><h3>Receive support</h3><p>Supporters contribute through Mobile Money, with transaction verification built into the final payment flow.</p></div></div></section>

    <section id="learn" className="section light-section page-pad"><div className="section-heading"><div><div className="eyebrow">Learn and grow</div><h2 className="section-title">Learn a skill. Build a trade.</h2></div><p className="section-subtitle">Practical knowledge helps turn a good idea into a stronger business. Each resource opens in a new tab.</p></div><div className="learning-grid">{learningResources.map(resource=><article className="learning-card" key={resource.name}><div className="learning-card-top"><span className="learning-group">{resource.group}</span><h3>{resource.name}</h3></div><p>{resource.description}</p><div className="learning-links"><a href={resource.sourceUrl} target="_blank" rel="noreferrer">Read resource <span>↗</span></a><a href={resource.videoUrl} target="_blank" rel="noreferrer">Watch videos <span>↗</span></a></div></article>)}</div></section>

    <section id="discover" className="section page-pad"><div className="discover-head"><div><div className="eyebrow">Discover & support</div><h2 className="section-title">Businesses raising support now</h2><p className="section-subtitle">Find a business you believe in and help move it to its next milestone.</p></div><span className="live-pill"><i/> Live pitches</span></div><div className="discover-tools"><label className="search-box">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search businesses, entrepreneurs or locations"/></label><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="almost">Almost funded</option><option value="most">Most supported</option><option value="newest">Newest</option></select></div><div className="category-pills">{categories.map(c=><button className={category===c?"active":""} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div>
      <div className="cards">{filtered.map(c=><article className="card" key={c.id}><button className="card-image" onClick={()=>openCampaign(c)}><img src={c.image} alt={c.title}/><span className="image-overlay"><span className="category">{c.category}</span>{c.flagship&&<span className="tag">Flagship</span>}</span></button><div className="card-body"><div className="verified-line">{c.verified?<span>✓ Verified campaign</span>:<span className="pending">Review in progress</span>}<span>{c.location}</span></div><h3>{c.title}</h3><div className="name">{c.name}</div><p className="description">{c.description}</p><p className="use"><em>Use of funds: {c.use}</em></p><div className="progress"><i style={{width:`${Math.min(100,Math.round(c.raised/c.goal*100))}%`}}/></div><div className="raised"><strong>GHS {c.raised.toLocaleString()}</strong> of GHS {c.goal.toLocaleString()} <span>· {Math.min(100,Math.round(c.raised/c.goal*100))}%</span></div><div className="supporters-count">{c.supporters} supporters</div><button className="support-btn" onClick={()=>openSupport(c)}>{c.raised>=c.goal?"Support the business":"Support this business"} <span>→</span></button></div></article>)}</div>{filtered.length===0&&<div className="empty">No campaigns match your search yet. Try another category or search term.</div>}</section>

    <section id="supporters" className="supporters-section page-pad"><div className="section-heading"><div><div className="eyebrow">Community</div><h2 className="section-title">People backing real businesses</h2></div><p className="section-subtitle">Supporters help entrepreneurs move from a good idea to a practical next step.</p></div><div className="supporter-table">{liveSupporters.map((s,i)=><div className="supporter-row" key={s[0]}><div className="rank">{String(i+1).padStart(2,"0")}</div><div className="avatar">{s[0].charAt(0)}</div><div className="supporter-info"><div className="supporter-name">{s[0]}</div><div className="supporter-meta">{s[1]} · backed {s[2]} entrepreneurs</div></div><div className="supporter-total">GHS {s[3].toLocaleString()}</div></div>)}</div></section>

    <section id="trust" className="trust-section page-pad"><div className="trust-copy"><div className="eyebrow">Trust is part of the product</div><h2 className="section-title">Know what your support is funding.</h2><p>Every campaign is designed around a clear goal, an itemized use of funds, and a public progress trail. Verification badges are reserved for campaigns that have passed the relevant review.</p><div className="trust-grid"><div><b>✓ Identity review</b><span>Entrepreneur details can be checked before publication.</span></div><div><b>✓ Business review</b><span>Campaign information and funding purpose are reviewed.</span></div><div><b>✓ Transaction records</b><span>Support activity can be matched to payment references.</span></div><div><b>✓ Report a concern</b><span>Supporters can flag a campaign for admin review.</span></div></div></div><div className="trust-card"><div className="shield">✓</div><h3>How Peer Pockets protects supporters</h3><ul><li>Clear funding goals</li><li>Itemized funding requests</li><li>Campaign review before publication</li><li>Payment confirmation and records</li><li>Admin oversight of the platform</li></ul></div></section>

    <section id="impact" className="section light-section page-pad"><div className="section-heading"><div><div className="eyebrow">Community impact</div><h2 className="section-title">Small contributions can move real businesses.</h2></div><p className="section-subtitle">Our impact dashboard is designed to show where the community is putting its support.</p></div><div className="impact-grid"><div><strong>{Number(impact.entrepreneurs_funded).toLocaleString()}+</strong><span>entrepreneurs funded</span></div><div><strong>GHS {Number(impact.support_mobilized).toLocaleString()}+</strong><span>support mobilized</span></div><div><strong>{Number(impact.supporters).toLocaleString()}+</strong><span>supporters engaged</span></div><div><strong>{Number(impact.average_progress)}%</strong><span>campaign progress average</span></div></div></section>

    <section className="stories section page-pad"><div className="section-heading"><div><div className="eyebrow">Community stories</div><h2 className="section-title">Why people choose to support</h2></div><p className="section-subtitle">A professional platform should make the human impact visible, not just the numbers.</p></div><div className="story-grid"><blockquote>“I wanted to support something I could understand. Seeing exactly what the money was for made the decision easy.”<footer>— Peer Pockets supporter</footer></blockquote><blockquote>“The campaign helped me explain my next step clearly instead of simply asking people for money.”<footer>— Young entrepreneur</footer></blockquote><blockquote>“The progress updates make it feel like you're building the business together.”<footer>— Community member</footer></blockquote></div></section>

    <section id="faq" className="section page-pad faq-section"><div className="section-heading"><div><div className="eyebrow">Questions</div><h2 className="section-title">Frequently asked questions</h2></div><p className="section-subtitle">A clear platform should make the important details easy to understand.</p></div><div className="faq-grid">{faqs.map((faq:any)=><details key={faq.question}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</div></section>

    <section className="cta-section page-pad"><div><div className="gold">For entrepreneurs</div><h2>Have a business that deserves a chance?</h2><p>Put a clear number behind your next step and let the community help you move.</p></div><button className="light-btn" onClick={()=>setModal("pitch")}>Pitch your business →</button></section>

    <footer className="footer"><div className="footer-main"><div className="footer-brand"><a href="#top" className="brand"><img src="/images/logo.svg" alt=""/><span>{platform.name||"Peer Pockets"}</span></a><p>Small capital. Real businesses. An entrepreneurship-focused community for young and micro entrepreneurs.</p><div className="footer-badges"><span>Entrepreneurship-focused</span><span>Community-powered</span></div></div><div className="footer-col"><h4>Explore</h4><a href="#discover">Businesses</a><a href="#supporters">Top supporters</a><a href="#how-it-works">How it works</a><a href="#impact">Our impact</a></div><div className="footer-col"><h4>For entrepreneurs</h4><button onClick={()=>setModal("pitch")}>Pitch your business</button><a href="#how-it-works">Funding guide</a><a href="#trust">Campaign guidelines</a></div><div className="footer-col"><h4>Support</h4><a href={`mailto:${platform.support_email||"hello@peerpockets.com"}`}>{platform.support_email||"hello@peerpockets.com"}</a><a href="#faq">FAQs</a><a className="admin-footer-link" href="/admin">Admin login →</a><span>{platform.country||"Ghana"}</span></div></div><div className="footer-bottom"><span>© 2026 Peer Pockets. All rights reserved.</span><span>Terms · Privacy · Refund policy · Responsible funding</span></div></footer>

    {notice&&<div className="toast">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
    {modal==="pitch"&&<div className="overlay"><div className="modal pitch-modal"><button className="close" onClick={()=>setModal(null)}>×</button><div className="pitch-intro"><div className="eyebrow">Entrepreneur application</div><h2>Pitch your business</h2><p>Peer Pocket connects entrepreneurs with people who want to support promising businesses and business ideas.</p><p className="pitch-note">Please answer honestly and provide accurate information. Every application is reviewed before a decision is made. Submitting this application does not guarantee funding or selection.</p></div><form onSubmit={submitPitch}>
      <fieldset><legend>About you</legend><label>Full name<input name="full_name" required/></label><label>Phone number (Mobile Money number)<input name="phone_number" type="tel" required/></label><label>Mobile Money network<select name="mobile_money_network" required><option value="">Select a network</option><option>MTN MoMo</option><option>Telecel Cash</option><option>AirtelTigo Money</option><option>Other</option></select></label><label>Email address <span className="field-note">(optional)</span><input name="email" type="email"/></label><label>Age<input name="age" type="number" min="1" required/></label><label>Location (Town/City)<input name="location" required/></label><label>Are you currently a student?<select name="is_student" value={pitchStudent} onChange={e=>setPitchStudent(e.target.value)} required><option value="">Select an answer</option><option value="yes">Yes</option><option value="no">No</option></select></label></fieldset>
      {pitchStudent === "yes" && <fieldset><legend>Student information</legend><p className="section-description">Complete this part only if you answered “Yes” to the previous question.</p><label>Which school/institution do you attend?<input name="school" required/></label></fieldset>}
      <fieldset><legend>Your business</legend><p className="section-description">Tell us about the business or business idea you are applying with.</p><label>Business name<input name="business_name" required/><small>If you do not have a registered business name yet, enter the name you intend to use.</small></label><label>What stage is your business currently at?<select name="business_stage" required><option>Just an idea</option><option>Just started: less than 6 months</option><option>Established: 6 months or more</option></select></label><label>What category best describes your business?<select name="category" required><option>Trading/Retail</option><option>Food & Beverage</option><option>Agriculture</option><option>Fashion & Beauty</option><option>Manufacturing</option><option>Services</option><option>Technology</option><option>Education</option><option>Transportation/Logistics</option><option>Other</option></select></label><label>In 2 to 3 sentences, describe your business.<textarea name="business_description" required rows={4}/></label><label>How long have you been running this business?<input name="business_duration" required/><small>If this is only an idea, write “Not started yet.”</small></label><label>Upload a photo of your business, product, or workspace <span className="field-note">(optional)</span><input name="business_photo" type="file" accept="image/*"/><small>Upload a clear photo that helps us understand your business. This question is optional.</small></label></fieldset>
      <fieldset><legend>The funding ask</legend><p className="section-description">Tell us exactly how the GHS 1,000 would help your business.</p><label>How will you use the GHS 1,000 if you are selected?<textarea name="funding_use" required rows={4}/></label><label>Break down exactly how you will use the GHS 1,000.<textarea name="funding_breakdown" required rows={4}/><small>Example: GHS 600 for stock, GHS 250 for equipment and GHS 150 for transportation.</small></label><label>What will this funding allow you to do that you cannot do right now?<textarea name="funding_difference" required rows={4}/></label><label>What result do you expect to achieve with the GHS 1,000?<textarea name="funding_result" required rows={4}/></label></fieldset>
      <fieldset><legend>Your story</legend><p className="section-description">Help us understand you, your motivation and your business journey.</p><label>Why did you start this business?<textarea name="motivation" required rows={4}/></label><label>What is the biggest challenge you are facing right now?<textarea name="challenge" required rows={4}/></label><label>What makes you or your business deserving of this support?<textarea name="deserving" required rows={4}/></label><label>Is there anything else you would like supporters to know about you or your business? <span className="field-note">(optional)</span><textarea name="additional_information" rows={4}/></label></fieldset>
      <fieldset><legend>Verification</legend><p className="section-description">This information helps us with the application review process.</p><label>Do you have a valid form of identification?<select name="has_identification" required><option value="">Select an answer</option><option>Yes</option><option>No</option></select><small>Examples include Ghana Card, passport or other valid identification.</small></label><label>Are you 18 years or older?<select name="is_adult" value={pitchAdult} onChange={e=>setPitchAdult(e.target.value)} required><option value="">Select an answer</option><option value="yes">Yes</option><option value="no">No</option></select></label></fieldset>
      {pitchAdult === "no" && <fieldset><legend>Parent or guardian information</legend><p className="section-description">This part is required only for applicants under 18.</p><label>Parent or guardian full name<input name="guardian_name" required/></label><label>Parent or guardian phone number<input name="guardian_phone" type="tel" required/></label></fieldset>}
      <fieldset className="consent-panel"><legend>Before you submit</legend><p className="section-description">Please review and accept the statements below.</p><label className="checkbox-label"><input name="accuracy_consent" type="checkbox" value="I agree" required/> I confirm that all information provided in this application is true and accurate to the best of my knowledge.</label><label className="checkbox-label"><input name="selection_consent" type="checkbox" value="I agree" required/> I understand that submitting this application does not guarantee funding or selection.</label><label className="checkbox-label"><input name="funds_consent" type="checkbox" value="I agree" required/> I agree to use any funds received for the purpose described in my application and to provide an update on how the funds were used if requested.</label><label className="checkbox-label"><input name="publicity_consent" type="checkbox" value="I agree"/> I consent to Peer Pocket sharing my name, business, photographs and business story on the Peer Pocket platform and social media for promotional and storytelling purposes.</label><label className="checkbox-label"><input name="disclaimer_consent" type="checkbox" value="I agree" required/> I understand that Peer Pocket facilitates connections between supporters and entrepreneurs and does not guarantee business outcomes or independently verify every claim made in this application.</label><label>How did you hear about Peer Pocket?<select name="referral_source" required><option value="">Select an option</option><option>TikTok</option><option>Instagram</option><option>Facebook</option><option>YouTube</option><option>WhatsApp</option><option>X</option><option>Friend or family</option><option>Peer Pocket event</option><option>Other</option></select></label></fieldset>
      <button className="support-btn" type="submit" disabled={pitchSending}>{pitchSending ? "Submitting…" : "Submit application →"}</button></form></div></div>}
    {modal==="campaign"&&selected&&<div className="overlay"><div className="modal campaign-modal"><button className="close" onClick={()=>setModal(null)}>×</button><img className="detail-image" src={selected.image} alt=""/><div className="eyebrow">{selected.category}</div><h2>{selected.title}</h2><div className="detail-by">{selected.name} · {selected.location} {selected.verified&&<span>✓ Verified</span>}</div><p>{selected.description}</p><div className="detail-stats"><div><strong>GHS {selected.raised.toLocaleString()}</strong><span>raised</span></div><div><strong>GHS {selected.goal.toLocaleString()}</strong><span>goal</span></div><div><strong>{selected.supporters}</strong><span>supporters</span></div></div><div className="detail-box"><b>What the funding will do</b><p>{selected.use}</p></div><div className="detail-box"><b>Latest update</b><p>{selected.update}</p></div><button className="support-btn" onClick={()=>openSupport(selected)}>Support this business →</button></div></div>}
    {modal==="support"&&selected&&<div className="overlay"><div className="modal"><button className="close" onClick={()=>setModal(null)}>×</button><div className="eyebrow">Support {selected.name}</div><h2>{selected.title}</h2><p>Enter the amount and your Mobile Money number. For now, send the contribution to Peer Pockets's Mobile Money number below. We will replace this with automatic Request-to-Pay when the payment provider is connected.</p><label>Support amount (GHS)<input type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="100"/></label><div className="amounts">{[50,100,200,500].map(v=><button key={v} onClick={()=>setAmount(String(v))}>GHS {v}</button>)}</div><label>Your Mobile Money number<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="024 XXX XXXX"/></label><div className="recipient-box"><div className="momo-label">PEER POCKETS MOBILE MONEY</div><strong>050 012 6026</strong><span>Send your contribution to this number using your preferred network.</span></div><label>Network<select value={senderNetwork} onChange={e=>setSenderNetwork(e.target.value)}><option>MTN Mobile Money</option><option>Telecel Cash</option><option>AT Money</option></select></label><button className="support-btn" onClick={beginPayment}>Continue to payment →</button>{paymentState!=="idle"&&<div className="momo-box"><div className="momo-label">PAYMENT STATUS</div><div className="momo-number">GHS {Number(amount||0).toLocaleString()}</div><div className="momo-network">{senderNetwork} · {phone}</div><p>{notice}</p>{paymentState==="waiting"&&<><div className="confirmation-box"><b>Reference confirmation</b><p>For the current prototype, enter the transaction/reference number after completing the transfer. When the real Request-to-Pay integration is enabled, this manual step will be replaced by automatic verification.</p><input value={paymentReference} onChange={e=>setPaymentReference(e.target.value)} placeholder="Transaction / reference number"/><button className="support-btn" onClick={confirmPayment}>Confirm payment →</button></div></>}{paymentState==="success"&&<div className="success-note">✓ Confirmation received. The admin/payment system can verify and credit the campaign.</div>}</div>}</div></div>}
  </main>;
}
